"".Add STEXT nosplit size=19 args=0x18 locals=0x0 funcid=0x0
	0x0000 00000 (ex0.go:5)	TEXT	"".Add(SB), NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (ex0.go:5)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (ex0.go:5)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (ex0.go:6)	MOVQ	"".b+16(SP), AX
	0x0005 00005 (ex0.go:6)	MOVQ	"".a+8(SP), CX
	0x000a 00010 (ex0.go:6)	ADDQ	CX, AX
	0x000d 00013 (ex0.go:6)	MOVQ	AX, "".~r2+24(SP)
	0x0012 00018 (ex0.go:6)	RET
	0x0000 48 8b 44 24 10 48 8b 4c 24 08 48 01 c8 48 89 44  H.D$.H.L$.H..H.D
	0x0010 24 18 c3                                         $..
"".main STEXT size=155 args=0x0 locals=0x58 funcid=0x0
	0x0000 00000 (ex0.go:9)	TEXT	"".main(SB), ABIInternal, $88-0
	0x0000 00000 (ex0.go:9)	MOVQ	TLS, CX
	0x0009 00009 (ex0.go:9)	PCDATA	$0, $-2
	0x0009 00009 (ex0.go:9)	MOVQ	(CX)(TLS*2), CX
	0x0010 00016 (ex0.go:9)	PCDATA	$0, $-1
	0x0010 00016 (ex0.go:9)	CMPQ	SP, 16(CX)
	0x0014 00020 (ex0.go:9)	PCDATA	$0, $-2
	0x0014 00020 (ex0.go:9)	JLS	145
	0x0016 00022 (ex0.go:9)	PCDATA	$0, $-1
	0x0016 00022 (ex0.go:9)	SUBQ	$88, SP
	0x001a 00026 (ex0.go:9)	MOVQ	BP, 80(SP)
	0x001f 00031 (ex0.go:9)	LEAQ	80(SP), BP
	0x0024 00036 (ex0.go:9)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0024 00036 (ex0.go:9)	FUNCDATA	$1, gclocals·f207267fbf96a0178e8758c6e3e0ce28(SB)
	0x0024 00036 (ex0.go:9)	FUNCDATA	$2, "".main.stkobj(SB)
	0x0024 00036 (ex0.go:11)	MOVQ	$9, (SP)
	0x002c 00044 (ex0.go:11)	PCDATA	$1, $0
	0x002c 00044 (ex0.go:11)	CALL	runtime.convT64(SB)
	0x0031 00049 (ex0.go:11)	MOVQ	8(SP), AX
	0x0036 00054 (ex0.go:11)	XORPS	X0, X0
	0x0039 00057 (ex0.go:11)	MOVUPS	X0, ""..autotmp_17+64(SP)
	0x003e 00062 (ex0.go:11)	LEAQ	type.int(SB), CX
	0x0045 00069 (ex0.go:11)	MOVQ	CX, ""..autotmp_17+64(SP)
	0x004a 00074 (ex0.go:11)	MOVQ	AX, ""..autotmp_17+72(SP)
	0x004f 00079 (<unknown line number>)	NOP
	0x004f 00079 ($GOROOT\src\fmt\print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0056 00086 ($GOROOT\src\fmt\print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x005d 00093 ($GOROOT\src\fmt\print.go:274)	MOVQ	CX, (SP)
	0x0061 00097 ($GOROOT\src\fmt\print.go:274)	MOVQ	AX, 8(SP)
	0x0066 00102 ($GOROOT\src\fmt\print.go:274)	LEAQ	""..autotmp_17+64(SP), AX
	0x006b 00107 ($GOROOT\src\fmt\print.go:274)	MOVQ	AX, 16(SP)
	0x0070 00112 ($GOROOT\src\fmt\print.go:274)	MOVQ	$1, 24(SP)
	0x0079 00121 ($GOROOT\src\fmt\print.go:274)	MOVQ	$1, 32(SP)
	0x0082 00130 ($GOROOT\src\fmt\print.go:274)	CALL	fmt.Fprintln(SB)
	0x0087 00135 (ex0.go:11)	MOVQ	80(SP), BP
	0x008c 00140 (ex0.go:11)	ADDQ	$88, SP
	0x0090 00144 (ex0.go:11)	RET
	0x0091 00145 (ex0.go:11)	NOP
	0x0091 00145 (ex0.go:9)	PCDATA	$1, $-1
	0x0091 00145 (ex0.go:9)	PCDATA	$0, $-2
	0x0091 00145 (ex0.go:9)	CALL	runtime.morestack_noctxt(SB)
	0x0096 00150 (ex0.go:9)	PCDATA	$0, $-1
	0x0096 00150 (ex0.go:9)	JMP	0
	0x0000 65 48 8b 0c 25 28 00 00 00 48 8b 89 00 00 00 00  eH..%(...H......
	0x0010 48 3b 61 10 76 7b 48 83 ec 58 48 89 6c 24 50 48  H;a.v{H..XH.l$PH
	0x0020 8d 6c 24 50 48 c7 04 24 09 00 00 00 e8 00 00 00  .l$PH..$........
	0x0030 00 48 8b 44 24 08 0f 57 c0 0f 11 44 24 40 48 8d  .H.D$..W...D$@H.
	0x0040 0d 00 00 00 00 48 89 4c 24 40 48 89 44 24 48 48  .....H.L$@H.D$HH
	0x0050 8b 05 00 00 00 00 48 8d 0d 00 00 00 00 48 89 0c  ......H......H..
	0x0060 24 48 89 44 24 08 48 8d 44 24 40 48 89 44 24 10  $H.D$.H.D$@H.D$.
	0x0070 48 c7 44 24 18 01 00 00 00 48 c7 44 24 20 01 00  H.D$.....H.D$ ..
	0x0080 00 00 e8 00 00 00 00 48 8b 6c 24 50 48 83 c4 58  .......H.l$PH..X
	0x0090 c3 e8 00 00 00 00 e9 65 ff ff ff                 .......e...
	rel 2+0 t=25 type.int+0
	rel 2+0 t=25 type.*os.File+0
	rel 12+4 t=17 TLS+0
	rel 45+4 t=8 runtime.convT64+0
	rel 65+4 t=16 type.int+0
	rel 82+4 t=16 os.Stdout+0
	rel 89+4 t=16 go.itab.*os.File,io.Writer+0
	rel 131+4 t=8 fmt.Fprintln+0
	rel 146+4 t=8 runtime.morestack_noctxt+0
os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0 funcid=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·e6397a44f8e1b6e77d0f200b4fba5269(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	XORPS	X0, X0
	0x0010 00016 (<autogenerated>:1)	MOVUPS	X0, "".~r0+16(SP)
	0x0015 00021 (<autogenerated>:1)	JMP	os.(*file).close(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 0f 57 c0  H.D$.H..H.D$..W.
	0x0010 0f 11 44 24 10 e9 00 00 00 00                    ..D$......
	rel 22+4 t=8 os.(*file).close+0
os.(*File).isdir STEXT dupok nosplit size=23 args=0x10 locals=0x0 funcid=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).isdir(SB), DUPOK|NOSPLIT|ABIInternal, $0-16
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·1a65e721a2ccc325b382662e7ffee780(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	MOVB	$0, "".~r0+16(SP)
	0x0012 00018 (<autogenerated>:1)	JMP	os.(*file).isdir(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 c6 44 24  H.D$.H..H.D$..D$
	0x0010 10 00 e9 00 00 00 00                             .......
	rel 19+4 t=8 os.(*file).isdir+0
go.cuinfo.packagename. SDWARFCUINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
""..inittask SNOPTRDATA size=32
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 fmt..inittask+0
go.info."".Add$abstract SDWARFABSFCN dupok size=25
	0x0000 04 2e 41 64 64 00 01 01 11 61 00 00 00 00 00 00  ..Add....a......
	0x0010 11 62 00 00 00 00 00 00 00                       .b.......
	rel 0+0 t=24 type.int+0
	rel 12+4 t=31 go.info.int+0
	rel 20+4 t=31 go.info.int+0
go.info.fmt.Println$abstract SDWARFABSFCN dupok size=42
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 6c 6e 00 01 01 11  .fmt.Println....
	0x0010 61 00 00 00 00 00 00 11 6e 00 01 00 00 00 00 11  a.......n.......
	0x0020 65 72 72 00 01 00 00 00 00 00                    err.......
	rel 0+0 t=24 type.[]interface {}+0
	rel 0+0 t=24 type.error+0
	rel 0+0 t=24 type.int+0
	rel 19+4 t=31 go.info.[]interface {}+0
	rel 27+4 t=31 go.info.int+0
	rel 37+4 t=31 go.info.error+0
runtime.nilinterequal·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.nilinterequal+0
runtime.memequal64·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.memequal64+0
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 08 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.nilinterequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 08 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
	0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 bf 03 a8 35 08 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.nilinterequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 44+4 t=6 type.*[1]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
	rel 0+8 t=1 type.io.Writer+0
	rel 8+8 t=1 type.*os.File+0
	rel 24+8 t=1 os.(*File).Write+0
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·f207267fbf96a0178e8758c6e3e0ce28 SRODATA dupok size=9
	0x0000 01 00 00 00 02 00 00 00 00                       .........
"".main.stkobj SRODATA static size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
gclocals·e6397a44f8e1b6e77d0f200b4fba5269 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 01 00                    ..........
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·1a65e721a2ccc325b382662e7ffee780 SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 01 00                    ..........
